#!/bin/bash

killall chuck &> /dev/null

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo $DIR
cd $DIR

OPTIONS="--adaptive:256 --in:1 --out:2 --dac:1 --adc:3"
CK_FILES="Std2 Gaussian CtlOnePole gfx SmeakySynth FilterStack XSynth SmeakyControl"

chuck $OPTIONS $@ $CK_FILES

killall chuck &> /dev/null
